version: '3.3'

services:
  db:
    image: mysql:8.0.35
    ports:
      - "53306:3306"
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret
      - MYSQL_USER=zmarket
      - MYSQL_PASSWORD=localZmarket
      - MYSQL_DATABASE=market